image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    PUBLIC_URL:  /stock-market-dashboard
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - develop
