image: node

stages:
  - build

  - test

  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build

test:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  script:
    - rm -rf dist
    - mv build dist
  artifacts:
    paths:
      - dist
  only:
    - develop
