image: node
stages:
  - test

  - deploy

testing:
  stage: test
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - public

deploy:
  stage: deploy

  script:
    - npm run build
    - rm -rf public
    - mv dist public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public

  only:
    - develop
