image: node

stages:
  - build

  - test

  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  script:
   - rm -rf public
   - mv dist public  
  artifacts:
    paths:
      - public
  only:
    - develop
