image: node

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    GIT_STRATEGY: none 
    PUBLIC_URL:  http://gitlab-react-page.garrick.monster
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - develop
