image: node

stages:
  - build

  - test

  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build

testing:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run test

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - develop
