stages:
  - build
  - deploy
build:
  image: node:latest    
  stage: build
  variables: 
    PUBLIC_URL: https://sashot.gitlab.io/stock-market-dashboard/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none       
  script:
  - rm -rf public
  - mv dist public    
  artifacts:
    paths:
      - public
